name: "Argus PR Reviewer"
description: "AI-powered pull request reviews that understand your codebase."

branding:
  icon: "eye"
  color: "orange"

inputs:
  mode:
    description: "Operating mode: review (PR review), index (incremental update), bootstrap (full re-index)"
    required: false
    default: "review"
  anthropic_api_key:
    description: "Anthropic API key (required for Anthropic models)"
    required: false
  openai_api_key:
    description: "OpenAI API key (required for OpenAI models)"
    required: false
  google_api_key:
    description: "Google API key (required for Gemini models)"
    required: false

runs:
  using: "docker"
  image: "docker://ghcr.io/sudzxd/argus:latest"
  env:
    GITHUB_TOKEN: ${{ github.token }}
    INPUT_MODE: ${{ inputs.mode }}
    ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    GOOGLE_API_KEY: ${{ inputs.google_api_key }}
