name: Bug Report
description: Report a bug in Argus
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Configure Argus with ...
        2. Open a PR that ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include logs or screenshots if available.
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: Model / Provider
      description: Which LLM model and provider were you using?
      placeholder: "e.g. google-gla:gemini-2.5-flash"
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Argus Version
      description: Version or commit SHA of Argus.
      placeholder: "e.g. v0.2.0 or abc1234"
    validations:
      required: false
